server:
  port: 9000

spring:
  application:
    name: CLOUD-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/v1/hotels/**, /api/v1/hotel-comments/**, /api/v1/attachments/**

        - id: tourist-service
          uri: lb://TOURIST-SERVICE
          predicates:
            - Path=/api/v1/tourists/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost
